name: My Deployment Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set Deploy End Time
      run: |
        echo "DEPLOY_END_TIME=$(date +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

    - name: Use Deploy End Time
      run: |
        echo "Deployment ended at $DEPLOY_END_TIME"
